"""add_preferred_report_currency_to_users

Revision ID: c69d74133aab
Revises: 60b56fe97635
Create Date: 2025-10-26 11:06:23.696802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d74133aab'
down_revision: Union[str, None] = '60b56fe97635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_report_currency', sa.String(length=3), nullable=False, server_default='RSD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_report_currency')
    # ### end Alembic commands ###

