"""initial_schema

Revision ID: 5be9eae5b608
Revises: 
Create Date: 2025-10-26 00:28:19.420675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be9eae5b608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', name='transactiontype'), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'base', 'date', name='uix_currency_base_date')
    )
    op.create_index(op.f('ix_fx_rates_currency'), 'fx_rates', ['currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_date'), 'fx_rates', ['date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', 'REVERSAL', 'SETTLEMENT', name='transactiontypeenum'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_at_time'), 'transactions', ['at_time'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO categories (name, transaction_type, icon, is_default) VALUES
        -- Expense categories
        ('Food', 'EXPENSE', '🍔', true),
        ('Transport', 'EXPENSE', '🚗', false),
        ('Coffee', 'EXPENSE', '☕', false),
        ('Shopping', 'EXPENSE', '🛍️', false),
        ('Bills', 'EXPENSE', '💡', false),
        ('Entertainment', 'EXPENSE', '🎬', false),
        ('Health', 'EXPENSE', '🏥', false),
        ('Other', 'EXPENSE', '📝', false),
        -- Income categories
        ('Salary', 'INCOME', '💰', true),
        ('Freelance', 'INCOME', '💼', false),
        ('Gift', 'INCOME', '🎁', false),
        ('Investment', 'INCOME', '📈', false),
        ('Other Income', 'INCOME', '💵', false);
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_at_time'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fx_rates_date'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('categories')
    # ### end Alembic commands ###

