"""add_debts_table

Revision ID: b2524aad6a65
Revises: e5f449cc5f34
Create Date: 2025-10-26 14:16:41.514871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2524aad6a65'
down_revision: Union[str, None] = 'e5f449cc5f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creditor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fx_rate_to_eur', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('related_transaction_id', sa.UUID(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creditor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debtor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_creditor_user_id'), 'debts', ['creditor_user_id'], unique=False)
    op.create_index(op.f('ix_debts_debtor_user_id'), 'debts', ['debtor_user_id'], unique=False)
    op.create_index(op.f('ix_debts_is_settled'), 'debts', ['is_settled'], unique=False)
    op.alter_column('categories', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='NULL for template categories; user_id for user-specific categories. Migration created 14 user categories.',
               existing_nullable=True)
    # Add related_debt_id column to transactions
    op.add_column('transactions', sa.Column('related_debt_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_transactions_related_debt_id', 'transactions', 'debts', ['related_debt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_related_debt_id', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'related_debt_id')
    op.alter_column('categories', 'user_id',
               existing_type=sa.BIGINT(),
               comment='NULL for template categories; user_id for user-specific categories. Migration created 14 user categories.',
               existing_nullable=True)
    op.drop_index(op.f('ix_debts_is_settled'), table_name='debts')
    op.drop_index(op.f('ix_debts_debtor_user_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_creditor_user_id'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###

